apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeName: worker1 
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "k8s_db"
        # --- AJOUT DU MONTAGE DU VOLUME DANS LE CONTENEUR ---
        volumeMounts:
        - name: mysql-nfs-storage
          mountPath: /var/lib/mysql
      # --- DÉFINITION DU VOLUME LIÉ AU PVC ---
      volumes:
      - name: mysql-nfs-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-nfs # Ce nom doit être le même que dans ton nfs-pv.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP 
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306